---
- name: Create CA cert file from variable content
  copy: >
    content={{ __my_openvpn_instance.openvpn_ca_cert }}
    dest={{openvpn_system_etcdir }}/{{ __openvpn_service_name }}/{{ __my_openvpn_instance.openvpn_keydir }}/ca.crt
    mode=0600
    owner=root
    group={{ openvpn_root_group }}
  register: taskresult

- include: detect_instance_update.yml

- name: Create server key file from variable content
  copy: >
    content={{ __my_openvpn_instance.openvpn_server_key }}
    dest={{openvpn_system_etcdir }}/{{ __openvpn_service_name }}/server.key
    mode=0600
    owner=root
    group={{ openvpn_root_group }}
  register: taskresult

- include: detect_instance_update.yml

- name: Create crl file from variable content
  copy: >
    content={{ __my_openvpn_instance.openvpn_crl }}
    dest={{ openvpn_system_etcdir }}/{{ __openvpn_service_name }}/{{ __my_openvpn_instance.openvpn_keydir }}/crl.pem
    mode=0600
    owner=root
    group={{ openvpn_root_group }}
  register: taskresult

- include: detect_instance_update.yml

