---
- name: Install openvpn (OpenBSD)
  openbsd_pkg: name=openvpn state=present

- name: Install openvpn ldap (OpenBSD)
  openbsd_pkg: name=openvpn-auth-ldap state=present
  when: __my_openvpn_instance.openvpn_use_ldap

- name: Install easyrsa (OpenBSD)
  openbsd_pkg: name=easy-rsa state=present
  when: 
   - not __my_openvpn_instance.openvpn_use_external_pki
