---
# tasks file for boxeman.openvpn
- name: Gathering OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: 'true'
  tags: [ 'openvpn' ]

- name: setup name of service default instance
  set_fact:
    __openvpn_service_name: "{{ openvpn_default_service_name }}"
  when: openvpn_instance_name|default('default') == 'default'
  tags: ['openvpn']

- name:  setup name of service for named instance
  set_fact:
    __openvpn_service_name: "openvpn_{{ openvpn_instance_name }}"
  when: openvpn_instance_name != 'default'
  tags: ['openvpn']

- name: Stop/disable service instance
  service: name="{{ __openvpn_service_name }}" state=stopped  enabled=no
  when: not openvpn_role_enabled
  tags: ['openvpn']

- include: openvpn.yml
  when: openvpn_role_enabled
  tags: ['openvpn']


